# Generated by Django 6.1.1 on 2026-09-09 20:49

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('publish', models.DateField(db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
    ]
