# Generated by Django 6.1.1 on 2026-09-25 22:49

from django.db import migrations

from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_options_post_tags'),
    ]

    operations = [
        TrigramExtension() 
    ]
