# Generated by Django 6.1.1 on 2026-10-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
