# Generated by Django 6.1.1 on 2026-10-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_name_comment_username_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
